version: '3.8'
services:
  mysql_db_container:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - ./tmpdb:/var/lib/mysql
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080
# #########################################
# #   Setup server container
# #########################################
#   server:
#     depends_on:
#       - mysqldb     
#     build: ./server
#     restart: unless-stopped
#     env_file: ./.env
#     ports:
#       - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
#     environment:
#       - DB_HOST=mysqldb
#       - DB_USER=$MYSQLDB_USER
#       - DB_PASSWORD=$MYSQL_PASS
#       - DB_NAME=$MYSQLDB_DATABASE
#       - DB_PORT=3036
#     networks:
#       - backend
#       - frontend
#     stdin_open: true
#     tty: true

# #########################################
# #   Setup client container
# #########################################
#   client:
#     depends_on:
#       - server
#     build:
#       context: ./client
#       args:
#         - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
#     ports:
#       - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
#     networks:
#       - frontend  
networks:
  backend:
  frontend: